name: push_puzzle
description: A Flutter project for UAP Praktikum Mobile.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  flame: 1.6.0
  dart_console: ^1.1.0
  firebase_core: ^2.15.1
  firebase_auth: ^4.7.3
  google_sign_in: ^5.0.8
  shared_preferences: ^2.2.0
  firebase_messaging: 14.7.9
  flutter_local_notifications: ^15.1.0+1
  http: ^0.13.3
  intl: ^0.18.1
  webview_flutter: ^4.2.2
  appwrite: ^11.0.1
  image_picker: ^1.0.4
  path_provider: ^2.0.1
  audioplayers: ^5.2.1
  just_audio: ^0.9.36
  firebase_database: ^10.3.8

dev_dependencies:
  mockito: ^5.4.2
  build_runner: ^2.4.6
  firebase_auth_mocks: ^0.13.0
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/fonts/
    - assets/audio/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
