name: push_puzzle
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  flame: 1.6.0
  dart_console: ^1.1.0
  firebase_core: ^2.15.1
  firebase_auth: ^4.7.3
  google_sign_in: ^5.0.8
  shared_preferences: ^2.2.0
  firebase_messaging: 14.7.9
  flutter_local_notifications: ^15.1.0+1
  audio_service: ^0.18.12
  audioplayers: ^0.20.1
  assets_audio_player: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
    - assets/music/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
