// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANBobksqzBG07oxr_7X3BZGHC3Cmg_Z4c',
    appId: '1:46223375187:web:703c0f4a246ace011e3fa6',
    messagingSenderId: '46223375187',
    projectId: 'uap-project-94203',
    authDomain: 'uap-project-94203.firebaseapp.com',
    storageBucket: 'uap-project-94203.appspot.com',
    measurementId: 'G-R0JNXNVWSB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjpoZ5B7Kvpb5jKajnVSgvyLaWDLsCqU8',
    appId: '1:46223375187:android:488c3269ec4f583d1e3fa6',
    messagingSenderId: '46223375187',
    projectId: 'uap-project-94203',
    storageBucket: 'uap-project-94203.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDA7BbIsjqOlcpbpiMHUWPqS7Eh8lKMp64',
    appId: '1:46223375187:ios:3974a15676d490701e3fa6',
    messagingSenderId: '46223375187',
    projectId: 'uap-project-94203',
    storageBucket: 'uap-project-94203.appspot.com',
    iosBundleId: 'com.example.pushPuzzle.RunnerTests',
  );
}
